_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: true
element_name: url
time_limit: 2
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_personal_form: false
  node_announcement_form: false
  node_blog_post_form: false
  node_book_form: false
  node_job_form: false
  node_report_form: false
  node_topic_form: false
  node_training_form: false
